### ISSUE TITLE
Can't import iCal into Google Calendar

### ISSUE THREAD

**Issue by keenlooks** [sec-deadlines/sec-deadlines.github.io#162]
Downloaded deadlines-all.ical and tried to import into Google Calendar. Google Calendar says "Imported 0 out of 0 events. Unable to process your iCal/CSV file." Might be something wrong with iCal format?

Alternatively, an updated Google Calendar we could subscribe to would also be useful. 😃

**Comment by kaoudis** [comment]
plus one, would really like a google calendar or other calendar that can be subscribed to without static import~

**Comment by Enrico204** [comment]
The issue has been fixed now. I tried and the iCal can be imported successfully into Google Calendar :-)
