### ISSUE TITLE
Filter for TOP-4 security conferences

### ISSUE THREAD

**Issue by Alfusainey** [sec-deadlines/sec-deadlines.github.io#313]
The number of security & privacy conferences are growing on this page and it's sometimes difficult to track deadlines for the top security venues (Oakland, NDSS, CCS, and USENIX Security).

I think it will be a nice-to-have to add a filter to get the deadlines for only these four conferences.

**Comment by Enrico204** [comment]
I think that this feature can be implemented using a tag (see issue #66 )
