### ISSUE TITLE
S&P 2020 wrong date

### ISSUE THREAD

**Issue by frz-dev** [sec-deadlines/sec-deadlines.github.io#43]
S&P2020 deadline is wrong. The last term was 1 December 2019. 
1st of February is still valid for S&P2020 only for papers already submitted bur subject to revision.
Also, S&P2021 changed from a monthly to a quarterly submission, with the following deadlines:
    Quarter 1: March 5
    Quarter 2: June 4
    Quarter 3: September 3
    Quarter 4: December 3

So the 1st of February is not a deadline anymore (not for 2020 nor 2021)

**Comment by frz-dev** [comment]
I submitted a Pull request replacing the mistaken SP2020 with SP2021

**Comment by bogdan-kulynych** [comment]
Thanks, should be addressed now.
