### ISSUE TITLE
Usenix deadlines shown for last year's conference

### ISSUE THREAD

**Issue by alexeiZamyatin** [sec-deadlines/sec-deadlines.github.io#52]
Correct deadlines: https://www.usenix.org/conference/usenixsecurity21

**Comment by deescuderoo** [comment]
I came here to say the same! Made some plans based on this, what a shame.

**Comment by bogdan-kulynych** [comment]
@deescuderoo Very sorry for that. Fixing.

**Comment by deescuderoo** [comment]
@bogdan-kulynych Thanks for addressing the issue! However, if I read correctly the deadline still points to the 2020 version of the conference, but that one has no more deadlines. The next deadline is for the 2021 version of the conference (link https://www.usenix.org/conference/usenixsecurity21)
