### ISSUE TITLE
Wrong ordering on Chrome

### ISSUE THREAD

**Issue by Dbof** [sec-deadlines/sec-deadlines.github.io#54]
Hey there! I just noticed that the ordering of events is a bit off for Chromium-based browsers.

On **Chromium** 81.0.4044.138 and **Google Chrome** 83.0.4103.61: [deadlines-chromium](https://user-images.githubusercontent.com/6752553/83325573-75389980-a26d-11ea-82ea-bb3fe260044f.png)

While on **Firefox** 76.0 (64-bit), it seems to have the correct ordering: [deadlines-firefox](https://user-images.githubusercontent.com/6752553/83325574-75d13000-a26d-11ea-81a8-a772a241e169.png)

I deactivated any addons regarding script etc. The web console also does not show any errors. Anyone has the same problems or ideas how to fix this?

**Comment by clementfung** [comment]
Thanks a lot to #95, I believe this is fixed!
