### ISSUE TITLE
For updating postponed deadlines automatically

### ISSUE THREAD

**Issue by occia** [sec-deadlines/sec-deadlines.github.io#56]
I have no idea about your detail implementation.
Just find that it doesn't update the postponed [2021 Usenix Security Summer Deadline](https://www.usenix.org/conference/usenixsecurity21/call-for-papers) as the official website (and has passed 2 days since the postpone).
Is it possible to follow the updated deadline automatically?
Anyway, this repo is fantastic, love it :)

**Comment by occia** [comment]
#57 Found some one created a PR already.

**Comment by bogdan-kulynych** [comment]
Not really, all the updates have to be done manually by me or through pull
requests. It's hard to see for me how the process can be automated.

пн, 8 черв. 2020 о 18:14 Cen Zhang <notifications@github.com> пише:

**Comment by occia** [comment]
Seems problem has been solved, close.
