### ISSUE TITLE
The website is becoming outdated

### ISSUE THREAD

**Issue by ducalpha** [sec-deadlines/sec-deadlines.github.io#65]
As 2020 is coming to an end and conferences are now calling papers for 2021, the titles of the conferences are still in 2020 and becoming outdated.
For example, CCS and PETS are still listed for 2020.
![image](https://user-images.githubusercontent.com/3000864/101962013-099a9600-3bd9-11eb-9dcd-2e4f5630a8fb.png)
![image](https://user-images.githubusercontent.com/3000864/101962029-115a3a80-3bd9-11eb-9802-b52f1575df87.png)

**Comment by clementfung** [comment]
Hi! 

I too have noticed this and I've recently taken on maintenance duties to help out with the website. 
I'm hoping this will keep the website more up to date in the future, thanks!
